### ISSUE TITLE
Unimplemented printf specifier

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/frigg#14]
The following applications from `util-linux` use `$` while printing their help message.

- `mount`,
- `fdisk`,
- `choom`,
- `findmnt`,
- `flock`,
- `getopt`,
- `mountpoint`,
- `renice`,
- `umount`,
- `agetty`,
- `cfdisk`,
- `losetup`,
- `sfdisk`,
- `zramctl`.

The following is logged in E9 for all of them.
```
mlibc: Unknown printf terminator '36'
```

**Comment by avdgrinten** [comment]
AFAICT `$` is a POSIX extension that allows selecting an argument by index (e.g., `%5$` to select the fifth argument).
