### ISSUE TITLE
Frigg assertion failure during printing

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/frigg#16]
While testing out the fixes for #14, I ran into the following problem

```
../../../src/mlibc/subprojects/frigg/include/frg/printf.hpp:57: Assertion 'opts->arg_pos <= vsp->num_args' failed!
```

Tested with the `--help` commands of:
- `mount`,
- `fdisk`,
- `choom`,
- `findmnt`,
- `flock`,
- `getopt`,
- `mountpoint`,
- `renice`,
- `umount`,
- `agetty`,
- `cfdisk`,
- `losetup`,
- `sfdisk`,
- `zramctl`.

**Comment by Geertiebear** [comment]
Hm, could you find the invocation that causes this error in any one of those programs? One that contains positional arguments of course.
